version: '3'

services:
    web:
      build: .
      ports:
        - "4000:4000"
      volumes:
        - .:/app
      depends_on:
        - db  
        
    db:
      image: "postgres:latest"
      environment: 
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres